/**
 * Static file templates for generated client projects.
 *
 * These are the files that don't change per project: package.json,
 * tsconfig, tailwind config, postcss, etc. The composer (page.tsx,
 * layout.tsx) and the library source files are produced separately.
 */

import type { Project } from "../project/types";

const NEXT_VERSION = "^15.1.6";
const REACT_VERSION = "^19.0.0";
const TAILWIND_VERSION = "^3.4.15";
const FRAMER_VERSION = "^11.11.17";

/** Generate package.json for the client project. */
export function packageJsonFor(project: Project, slug: string): string {
  return JSON.stringify(
    {
      name: slug,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: NEXT_VERSION,
        react: REACT_VERSION,
        "react-dom": REACT_VERSION,
        "framer-motion": FRAMER_VERSION,
      },
      devDependencies: {
        "@types/node": "^22.9.0",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        autoprefixer: "^10.4.20",
        postcss: "^8.4.49",
        tailwindcss: TAILWIND_VERSION,
        typescript: "^5.6.3",
      },
    },
    null,
    2
  );
}

export const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: { remotePatterns: [{ protocol: "https", hostname: "**" }] },
};
module.exports = nextConfig;
`;

export const TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      target: "ES2020",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: { "@/*": ["./*"] },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  },
  null,
  2
);

export const POSTCSS_CONFIG = `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };
`;

export const TAILWIND_CONFIG = `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Library tokens — resolved at runtime from CSS vars set by
        // <LibraryRoot>. Do not hardcode hex values here.
        "lib-bg": "var(--lib-bg)",
        "lib-surface": "var(--lib-surface)",
        "lib-foreground": "var(--lib-foreground)",
        "lib-muted": "var(--lib-muted)",
        "lib-accent": "var(--lib-accent)",
        "lib-accent-foreground": "var(--lib-accent-foreground)",
        "lib-border": "var(--lib-border)",
      },
      fontFamily: {
        "lib-display": "var(--lib-font-display)",
        "lib-body": "var(--lib-font-body)",
      },
      ringColor: { "lib-accent": "var(--lib-accent)" },
    },
  },
  plugins: [],
};
export default config;
`;

export const GITIGNORE = `node_modules
/.next/
/out/
/build
.DS_Store
*.pem
.env*.local
.env
.vercel
*.tsbuildinfo
next-env.d.ts
`;

export const GLOBALS_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;

@import "./library.css";

html, body {
  background: var(--lib-bg);
  color: var(--lib-foreground);
  font-family: var(--lib-font-body);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
* { box-sizing: border-box; }
body { overflow-x: hidden; }
::selection { background: var(--lib-accent); color: var(--lib-accent-foreground); }
`;

export const README = (project: Project, slug: string) => `# ${project.form.business.name || slug}

Generated by Flowwwzy Studio on ${new Date().toISOString().slice(0, 10)}.
Project ID: ${project.id}

## Run locally

\`\`\`bash
npm install
npm run dev
\`\`\`

## Stack

- Next.js ${NEXT_VERSION}
- React ${REACT_VERSION}
- Tailwind ${TAILWIND_VERSION}
- Framer Motion ${FRAMER_VERSION}

## Editing content

Each section's content lives in \`app/page.tsx\` as a typed object.
Change the strings, add list items, or swap images directly there —
no design system files need touching.

To change theme (palette, fonts), edit the \`<LibraryRoot>\` props
in \`app/layout.tsx\`.
`;
